"""FlowCraft adapter for Node.js script: meme.mjs

Auto-generated by convert_skill.py.
Wraps CLI-arg Node.js script for stdin JSON interface.
"""

import json
import subprocess
import sys
from pathlib import Path

ORIGINAL = Path(__file__).parent / "meme.mjs"

def _params_to_args(params: dict) -> list:
    args = []
    for key, value in params.items():
        if key.startswith("_"):
            continue
        if isinstance(value, bool):
            if value:
                args.append(f"--{key}")
        elif isinstance(value, list):
            for v in value:
                args.extend([f"--{key}", str(v)])
        elif value is not None and value != "":
            args.extend([f"--{key}", str(value)])
    return args

def main():
    try:
        raw = sys.stdin.read()
        params = json.loads(raw) if raw.strip() else {}
    except Exception as e:
        print(json.dumps({"status": "error", "message": f"Invalid JSON: {e}"}))
        return

    args = ["node", str(ORIGINAL)] + _params_to_args(params)

    try:
        result = subprocess.run(args, capture_output=True, text=True, timeout=120,
                               cwd=str(Path(__file__).parent))
        output = result.stdout.strip()
        error = result.stderr.strip()

        if result.returncode == 0:
            try:
                payload = json.loads(output)
            except json.JSONDecodeError:
                payload = {"raw_output": output}
            payload["status"] = "success"
            print(json.dumps(payload, ensure_ascii=False))
        else:
            print(json.dumps({
                "status": "error", "returncode": result.returncode,
                "output": output[:10000], "error": error[:5000],
            }, ensure_ascii=False))
    except Exception as e:
        print(json.dumps({"status": "error", "message": str(e)}))

if __name__ == "__main__":
    main()
