"""FlowCraft adapter for OpenClaw script: model_usage.py

Auto-generated by convert_skill.py. Wraps CLI-arg script for stdin JSON interface.
"""

import json
import subprocess
import sys
from pathlib import Path

ORIGINAL = Path(__file__).parent / "model_usage.py"

def main():
    try:
        raw = sys.stdin.read()
        params = json.loads(raw) if raw.strip() else {}
    except Exception as e:
        print(json.dumps({"status": "error", "message": f"Invalid input JSON: {e}"}))
        return

    # Map JSON params to CLI args
    args = ["python", str(ORIGINAL)] + _build_args(params)

    try:
        result = subprocess.run(
            args,
            capture_output=True,
            text=True,
            timeout=120,
            cwd=str(Path(__file__).parent),
        )
        output = result.stdout.strip()
        error = result.stderr.strip()

        if result.returncode == 0:
            try:
                payload = json.loads(output)
            except json.JSONDecodeError:
                payload = {"raw_output": output}
            payload["status"] = "success"
            print(json.dumps(payload, ensure_ascii=False))
        else:
            print(json.dumps({
                "status": "error",
                "returncode": result.returncode,
                "output": output[:10000],
                "error": error[:5000],
            }, ensure_ascii=False))
    except subprocess.TimeoutExpired:
        print(json.dumps({"status": "error", "message": f"Script timed out after 120s"}))
    except Exception as e:
        print(json.dumps({"status": "error", "message": str(e)}))

if __name__ == "__main__":
    main()
