from enum import StrEnum


class TaskStatus(StrEnum):
    CREATED = "CREATED"
    INTENT_RECOGNIZED = "INTENT_RECOGNIZED"
    PLANNED = "PLANNED"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    EXECUTING = "EXECUTING"
    WAITING_TOOL = "WAITING_TOOL"
    OBSERVING = "OBSERVING"
    REPLANNING = "REPLANNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class StepStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    WAITING_TOOL = "WAITING_TOOL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TaskType(StrEnum):
    """任务类型 — 第二阶段扩展: SPREADSHEET_ANALYSIS, EMAIL_ASSISTANT, SCHEDULED_TASK, KNOWLEDGE_QA, MULTI_STEP_RESEARCH."""
    QA = "QA"
    FILE_TASK = "FILE_TASK"
    BROWSER_TASK = "BROWSER_TASK"
    LOCAL_OPERATION = "LOCAL_OPERATION"
    DOCUMENT_SUMMARY = "DOCUMENT_SUMMARY"
    WORKFLOW_AUTOMATION = "WORKFLOW_AUTOMATION"
    # 第二阶段扩展
    SPREADSHEET_ANALYSIS = "SPREADSHEET_ANALYSIS"
    EMAIL_ASSISTANT = "EMAIL_ASSISTANT"
    SCHEDULED_TASK = "SCHEDULED_TASK"
    KNOWLEDGE_QA = "KNOWLEDGE_QA"
    MULTI_STEP_RESEARCH = "MULTI_STEP_RESEARCH"


class PlanMode(StrEnum):
    DIRECT = "DIRECT"
    LINEAR = "LINEAR"
    DAG = "DAG"
    ITERATIVE = "ITERATIVE"


class PolicyDecisionValue(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
    REQUIRE_CLARIFICATION = "REQUIRE_CLARIFICATION"
    REQUIRE_SANDBOX = "REQUIRE_SANDBOX"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"

