#!/usr/bin/env python3
"""OpenClaw Skill → FlowCraft Skill Converter.

Converts an OpenClaw SKILL.md directory to FlowCraft-compatible format.
Handles:
  - Frontmatter translation (OpenClaw → FlowCraft fields)
  - Script interface adaptation (CLI args → stdin JSON)
  - JS/PS1 script wrapping (Python subprocess adapter)
  - Binary dependency conversion (requires.bins → exec instructions)
  - Reference file merging

Usage:
  python convert_skill.py <openclaw_skill_dir> --output <flowcraft_skills_dir>
                          [--category data|files|code|general]
                          [--mode auto|markdown|script|hybrid]
                          [--dry-run]
                          [--verbose]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Any


# ── Constants ──────────────────────────────────────────────

FLOWCRAFT_FRONTMATTER_TEMPLATE = """---
name: {name}
description: "{description}"
category: {category}
version: "1.0.0"
author: "openclaw-ported"
script_path: {script_path}
script_language: {script_language}
tags: {tags}
timeout_seconds: {timeout_seconds}
source: marketplace
enabled: true
---
"""

SCRIPT_ADAPTER_TEMPLATE = '''"""FlowCraft adapter for OpenClaw script: {original_script}

Auto-generated by convert_skill.py. Wraps CLI-arg script for stdin JSON interface.
"""

import json
import subprocess
import sys
from pathlib import Path

ORIGINAL = Path(__file__).parent / "{original_script}"

def main():
    try:
        raw = sys.stdin.read()
        params = json.loads(raw) if raw.strip() else {{}}
    except Exception as e:
        print(json.dumps({{"status": "error", "message": f"Invalid input JSON: {{e}}"}}))
        return

    # Map JSON params to CLI args
    args = {args_builder}

    try:
        result = subprocess.run(
            args,
            capture_output=True,
            text=True,
            timeout={timeout},
            cwd=str(Path(__file__).parent),
        )
        output = result.stdout.strip()
        error = result.stderr.strip()

        if result.returncode == 0:
            try:
                payload = json.loads(output)
            except json.JSONDecodeError:
                payload = {{"raw_output": output}}
            payload["status"] = "success"
            print(json.dumps(payload, ensure_ascii=False))
        else:
            print(json.dumps({{
                "status": "error",
                "returncode": result.returncode,
                "output": output[:10000],
                "error": error[:5000],
            }}, ensure_ascii=False))
    except subprocess.TimeoutExpired:
        print(json.dumps({{"status": "error", "message": f"Script timed out after {timeout}s"}}))
    except Exception as e:
        print(json.dumps({{"status": "error", "message": str(e)}}))

if __name__ == "__main__":
    main()
'''

# Category auto-detection keywords
CATEGORY_KEYWORDS = {
    "data": ["data", "csv", "json", "analyze", "statistics", "chart", "graph", "plot", "excel"],
    "code": ["code", "programming", "developer", "git", "github", "pr", "review", "test", "build", "debug"],
    "files": ["file", "rename", "move", "copy", "delete", "directory", "folder", "backup"],
    "network": ["web", "http", "api", "scrape", "download", "fetch", "url", "rest"],
    "text": ["text", "document", "markdown", "pdf", "docx", "summarize", "translate"],
    "media": ["image", "video", "audio", "screenshot", "diagram", "svg", "meme"],
    "system": ["shell", "command", "process", "service", "daemon", "monitor"],
    "general": [],
}


class SkillConverter:
    """Converts an OpenClaw skill directory to FlowCraft format."""

    def __init__(
        self,
        source_dir: str | Path,
        output_dir: str | Path,
        category: str = "general",
        mode: str = "auto",
        dry_run: bool = False,
        verbose: bool = False,
    ) -> None:
        self.source_dir = Path(source_dir)
        self.output_dir = Path(output_dir)
        self.category = category
        self.mode = mode  # auto | markdown | script | hybrid
        self.dry_run = dry_run
        self.verbose = verbose

        self.skill_name = self.source_dir.name
        self.skill_md_path = self.source_dir / "SKILL.md"
        self.scripts_dir = self.source_dir / "scripts"
        self.references_dir = self.source_dir / "references"
        self.assets_dir = self.source_dir / "assets"
        self.agents_dir = self.source_dir / "agents"

    def convert(self) -> dict[str, Any]:
        """Run full conversion. Returns summary dict."""
        result = {
            "skill_name": self.skill_name,
            "status": "success",
            "warnings": [],
            "actions": [],
        }

        if not self.skill_md_path.exists():
            result["status"] = "error"
            result["error"] = f"No SKILL.md found in {self.source_dir}"
            return result

        # 1. Parse OpenClaw SKILL.md
        frontmatter, body = self._parse_frontmatter()
        result["original_frontmatter"] = frontmatter

        # 2. Detect category if not specified
        if self.category == "general":
            self.category = self._detect_category(
                frontmatter.get("description", "") + " " + body[:500]
            )

        # 3. Determine conversion mode
        effective_mode = self._determine_mode(frontmatter)
        result["effective_mode"] = effective_mode

        if effective_mode is None:
            result["status"] = "skipped"
            result["reason"] = "OpenClaw-internal skill (skip)"
            return result

        # 4. Create output directory
        output_skill_dir = self.output_dir / self.skill_name
        if not self.dry_run:
            output_skill_dir.mkdir(parents=True, exist_ok=True)

        # 5. Handle scripts
        script_path = None
        script_language = "python"
        args_builder = ""

        if effective_mode in ("script", "hybrid"):
            script_result = self._convert_scripts(output_skill_dir)
            script_path = script_result.get("script_path")
            script_language = script_result.get("language", "python")
            args_builder = script_result.get("args_builder", "")
            result["actions"].append(script_result)

        # 6. Copy references as part of body
        if self.references_dir.exists():
            refs_text = self._merge_references()
            body += refs_text
            result["actions"].append(f"merged references ({len(list(self.references_dir.iterdir()))} files)")

        # 7. Handle binary dependencies → exec instructions in body
        bins = self._extract_bins(frontmatter)
        if bins:
            exec_instructions = self._generate_exec_instructions(bins)
            body = exec_instructions + "\n\n" + body
            result["actions"].append(f"generated exec instructions for bins: {bins}")

        # 8. Detect tags
        tags = self._detect_tags(frontmatter, body)

        # 9. Build FlowCraft frontmatter
        fc_frontmatter = FLOWCRAFT_FRONTMATTER_TEMPLATE.format(
            name=self.skill_name,
            description=frontmatter.get("description", f"Skill: {self.skill_name}").strip('"').replace('"', '\\"'),
            category=self.category,
            script_path=f'"{script_path}"' if script_path else '""',
            script_language=script_language if script_path else "none",
            tags=json.dumps(tags),
            timeout_seconds=120 if script_path else 60,
        )

        # 10. Write SKILL.md
        full_content = fc_frontmatter + "\n" + self._clean_body(body)
        result["output_size"] = len(full_content)

        if self.dry_run:
            result["action"] = f"[DRY RUN] Would create: {output_skill_dir}/SKILL.md ({len(full_content)} chars)"
        else:
            (output_skill_dir / "SKILL.md").write_text(full_content, encoding="utf-8")
            result["action"] = f"Created: {output_skill_dir}/SKILL.md ({len(full_content)} chars)"

        return result

    # ── Internal Methods ────────────────────────────────────

    def _parse_frontmatter(self) -> tuple[dict[str, Any], str]:
        """Parse YAML-like frontmatter from SKILL.md."""
        content = self.skill_md_path.read_text(encoding="utf-8")
        frontmatter: dict[str, Any] = {}
        body = content

        if content.startswith("---"):
            parts = content.split("---", 2)
            if len(parts) >= 3:
                # Simple YAML-like parser (avoid yaml dependency for converter)
                for line in parts[1].strip().split("\n"):
                    line = line.strip()
                    if ":" in line and not line.startswith("#"):
                        key, _, val = line.partition(":")
                        key = key.strip()
                        val = val.strip().strip('"').strip("'")
                        frontmatter[key] = val
                body = parts[2]

        return frontmatter, body

    def _determine_mode(self, frontmatter: dict) -> str | None:
        """Determine conversion mode based on skill content.

        Returns None if the skill should be skipped (OpenClaw-internal).
        """
        name = self.skill_name
        desc = frontmatter.get("description", "").lower()

        # Skip OpenClaw-internal skills
        internal_patterns = [
            "openclaw", "claw-score", "clawdtributor", "clawsweeper",
            "crabbox", "release-openclaw", "discord-clawd",
            "openclaw-ghsa", "openclaw-landable", "openclaw-parallels",
            "openclaw-pr-maintainer", "openclaw-qa", "openclaw-refactor",
            "openclaw-secret", "openclaw-small-bugfix", "openclaw-test",
            "parallels-discord", "control-ui-e2e", "channel-message",
            "discord-user-post", "telegram-crabbox", "verify-release",
        ]
        for pat in internal_patterns:
            if pat in name.lower() or (desc and pat in desc):
                if self.verbose:
                    print(f"  SKIP: {name} (OpenClaw-internal)")
                return None

        has_scripts = self.scripts_dir.exists() and any(
            f.endswith((".py", ".sh")) for f in os.listdir(self.scripts_dir)
        )
        has_js_scripts = self.scripts_dir.exists() and any(
            f.endswith((".mjs", ".js")) for f in os.listdir(self.scripts_dir)
        )

        if self.mode == "auto":
            if has_scripts or has_js_scripts:
                return "hybrid"
            return "markdown"

        return self.mode

    def _convert_scripts(self, output_skill_dir: Path) -> dict[str, Any]:
        """Convert scripts directory. Returns info about the conversion."""
        result = {
            "script_path": None,
            "language": "python",
            "args_builder": "",
        }

        if not self.scripts_dir.exists():
            return result

        output_scripts_dir = output_skill_dir / "scripts"
        if not self.dry_run:
            output_scripts_dir.mkdir(parents=True, exist_ok=True)

        # Find the main script
        script_files = list(self.scripts_dir.iterdir())
        python_files = [f for f in script_files if f.suffix == ".py"]
        js_files = [f for f in script_files if f.suffix in (".mjs", ".js")]
        bash_files = [f for f in script_files if f.suffix == ".sh"]
        ps_files = [f for f in script_files if f.suffix == ".ps1"]

        if python_files:
            main_script = python_files[0]
            result["language"] = "python"

            # Copy original script
            if not self.dry_run:
                shutil.copy2(main_script, output_scripts_dir / main_script.name)

            # Check if script uses argparse (needs stdin adapter)
            script_content = main_script.read_text(encoding="utf-8")
            uses_argparse = "argparse" in script_content or "ArgumentParser" in script_content

            if uses_argparse:
                # Generate adapter
                args_builder = self._infer_cli_args(script_content)
                adapter_content = SCRIPT_ADAPTER_TEMPLATE.format(
                    original_script=main_script.name,
                    args_builder=args_builder,
                    timeout=120,
                )
                adapter_name = "main.py"
                if not self.dry_run:
                    (output_scripts_dir / adapter_name).write_text(adapter_content, encoding="utf-8")
                result["script_path"] = f"scripts/{adapter_name}"
                result["args_builder"] = args_builder
            else:
                # Script already uses stdin JSON or is simple — use directly
                adapter_name = "main.py"
                if not self.dry_run:
                    if main_script.name != adapter_name:
                        shutil.copy2(main_script, output_scripts_dir / adapter_name)
                result["script_path"] = f"scripts/{adapter_name}"

        elif js_files:
            main_script = js_files[0]
            result["language"] = "python"  # We generate a Python adapter

            # Copy original JS script
            if not self.dry_run:
                shutil.copy2(main_script, output_scripts_dir / main_script.name)

            # Generate Python adapter that calls node
            args_builder = f'["node", str(ORIGINAL)] + _json_to_args(params)'
            adapter_content = SCRIPT_ADAPTER_TEMPLATE.format(
                original_script=main_script.name,
                args_builder=args_builder,
                timeout=120,
            )
            # Fix: node subprocess needs different handling
            adapter_content = adapter_content.replace(
                "subprocess.run(\n            args,",
                'subprocess.run(\n            ["node", str(ORIGINAL)] + _params_to_args(params),'
            )
            # Better: write a proper adapter
            adapter_content = self._generate_node_adapter(main_script.name)

            adapter_name = "main.py"
            if not self.dry_run:
                (output_scripts_dir / adapter_name).write_text(adapter_content, encoding="utf-8")
            result["script_path"] = f"scripts/{adapter_name}"

        elif bash_files:
            main_script = bash_files[0]
            result["language"] = "bash"
            if not self.dry_run:
                shutil.copy2(main_script, output_scripts_dir / "main.sh")
            result["script_path"] = "scripts/main.sh"

        return result

    def _generate_node_adapter(self, script_name: str) -> str:
        """Generate Python adapter for Node.js scripts."""
        return f'''"""FlowCraft adapter for Node.js script: {script_name}

Auto-generated by convert_skill.py.
Wraps CLI-arg Node.js script for stdin JSON interface.
"""

import json
import subprocess
import sys
from pathlib import Path

ORIGINAL = Path(__file__).parent / "{script_name}"

def _params_to_args(params: dict) -> list:
    args = []
    for key, value in params.items():
        if key.startswith("_"):
            continue
        if isinstance(value, bool):
            if value:
                args.append(f"--{{key}}")
        elif isinstance(value, list):
            for v in value:
                args.extend([f"--{{key}}", str(v)])
        elif value is not None and value != "":
            args.extend([f"--{{key}}", str(value)])
    return args

def main():
    try:
        raw = sys.stdin.read()
        params = json.loads(raw) if raw.strip() else {{}}
    except Exception as e:
        print(json.dumps({{"status": "error", "message": f"Invalid JSON: {{e}}"}}))
        return

    args = ["node", str(ORIGINAL)] + _params_to_args(params)

    try:
        result = subprocess.run(args, capture_output=True, text=True, timeout=120,
                               cwd=str(Path(__file__).parent))
        output = result.stdout.strip()
        error = result.stderr.strip()

        if result.returncode == 0:
            try:
                payload = json.loads(output)
            except json.JSONDecodeError:
                payload = {{"raw_output": output}}
            payload["status"] = "success"
            print(json.dumps(payload, ensure_ascii=False))
        else:
            print(json.dumps({{
                "status": "error", "returncode": result.returncode,
                "output": output[:10000], "error": error[:5000],
            }}, ensure_ascii=False))
    except Exception as e:
        print(json.dumps({{"status": "error", "message": str(e)}}))

if __name__ == "__main__":
    main()
'''

    def _infer_cli_args(self, script_content: str) -> str:
        """Infer CLI argument mapping for argparse-based scripts.

        Returns a Python expression string like:
            '["python", str(ORIGINAL), params.get("name", ""), "--path", params.get("path", ".")]'
        """
        # Try to extract argparse definitions
        args = []
        # Find add_argument calls
        for match in re.finditer(r"add_argument\(['\"]([^'\"]+)['\"]", script_content):
            arg_name = match.group(1)
            # Convert --arg-name to arg_name for params key
            key = arg_name.lstrip("-").replace("-", "_")
            if arg_name.startswith("--"):
                args.append(f'["--{arg_name.lstrip("-")}", str(params.get("{key}", ""))]')
            elif arg_name.startswith("-"):
                args.append(f'["-{arg_name.lstrip("-")}", str(params.get("{key}", ""))]')
            else:
                # Positional argument
                args.append(f'[str(params.get("{key}", ""))]')

        if not args:
            # Fallback: pass all params as --key value pairs
            return '["python", str(ORIGINAL)] + [item for k, v in params.items() for item in [f"--{k}", str(v)]]'

        # Build expression
        parts = ['["python", str(ORIGINAL)]']
        for arg_expr in args:
            parts.append(f" + ({arg_expr} if params.get(...) else [])")

        # Simplify to a cleaner form
        return '["python", str(ORIGINAL)] + _build_args(params)'

    def _merge_references(self) -> str:
        """Merge reference files into the body as appendices."""
        if not self.references_dir.exists():
            return ""

        parts = ["\n\n## References\n"]
        for ref_file in sorted(self.references_dir.iterdir()):
            if ref_file.suffix in (".md", ".txt"):
                ref_content = ref_file.read_text(encoding="utf-8", errors="replace")
                parts.append(f"\n### {ref_file.stem}\n")
                parts.append(ref_content[:3000])  # Truncate long refs
                if len(ref_content) > 3000:
                    parts.append("\n[... truncated]")
        return "\n".join(parts)

    def _extract_bins(self, frontmatter: dict) -> list[str]:
        """Extract required binaries from frontmatter."""
        bins = []
        requires_str = frontmatter.get("requires", "")
        if requires_str:
            # Try to parse {"bins": ["gh", "git"]} format
            match = re.search(r'"bins"\s*:\s*\[(.*?)\]', requires_str)
            if match:
                bins = [b.strip().strip('"').strip("'") for b in match.group(1).split(",")]
        return bins

    def _generate_exec_instructions(self, bins: list[str]) -> str:
        """Generate exec-based usage instructions for binary dependencies."""
        lines = [
            "## Required Tools",
            "",
            "This skill requires the following CLI tools to be installed:",
        ]
        for b in bins:
            lines.append(f"- `{b}`")
        lines.append("")
        lines.append("## Usage via exec")
        lines.append("")
        lines.append("When using this skill, call the required tools via the `exec` tool. Examples:")
        lines.append("")
        for b in bins[:3]:
            lines.append(f'- `exec "which {b}"` — verify {b} is installed')
        lines.append("")
        return "\n".join(lines)

    def _detect_category(self, text: str) -> str:
        """Auto-detect skill category from description text."""
        text_lower = text.lower()
        scores = {}
        for cat, keywords in CATEGORY_KEYWORDS.items():
            score = sum(1 for kw in keywords if kw in text_lower)
            if score > 0:
                scores[cat] = score
        if scores:
            return max(scores, key=scores.get)
        return "general"

    def _detect_tags(self, frontmatter: dict, body: str) -> list[str]:
        """Detect tags from skill metadata and content."""
        tags = []
        text = (frontmatter.get("description", "") + " " + body[:1000]).lower()

        tag_keywords = {
            "python": ["python", ".py"],
            "javascript": ["javascript", "node", ".js", ".mjs"],
            "bash": ["bash", "shell", ".sh"],
            "git": ["git", "github", "commit", "branch", "pr"],
            "api": ["api", "rest", "http", "endpoint"],
            "cli": ["cli", "command-line", "terminal"],
            "automation": ["automate", "automation", "workflow", "batch"],
            "documentation": ["document", "docs", "readme", "markdown"],
            "testing": ["test", "testing", "qa", "quality"],
            "code-review": ["review", "code review", "audit"],
        }
        for tag, keywords in tag_keywords.items():
            if any(kw in text for kw in keywords):
                tags.append(tag)
        return tags[:6]

    def _clean_body(self, body: str) -> str:
        """Clean the markdown body for FlowCraft compatibility."""
        # Remove OpenClaw-specific metadata blocks
        body = re.sub(r'##\s+metadata\s*\n.*?(?=\n##|\Z)', '', body, flags=re.I | re.S)
        # Fix {baseDir} references — keep as-is (FlowCraft compatible)
        return body.strip()


# ── CLI ─────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Convert OpenClaw skills to FlowCraft format")
    parser.add_argument("source", nargs="+", help="OpenClaw skill directories")
    parser.add_argument("--output", "-o", required=True, help="FlowCraft skills output directory")
    parser.add_argument("--category", "-c", default="general",
                       help="Skill category (data|code|files|network|text|media|system|general)")
    parser.add_argument("--mode", "-m", default="auto",
                       choices=["auto", "markdown", "script", "hybrid"],
                       help="Conversion mode")
    parser.add_argument("--dry-run", "-n", action="store_true", help="Preview only, no file writes")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")

    args = parser.parse_args()

    output_dir = Path(args.output)
    if not args.dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)

    total = 0
    converted = 0
    skipped = 0
    errors = 0

    for source in args.source:
        source_path = Path(source)
        if not source_path.is_dir():
            print(f"ERROR: Not a directory: {source}")
            errors += 1
            continue

        total += 1
        converter = SkillConverter(
            source_dir=source_path,
            output_dir=output_dir,
            category=args.category,
            mode=args.mode,
            dry_run=args.dry_run,
            verbose=args.verbose,
        )
        result = converter.convert()

        if result["status"] == "success":
            converted += 1
            print(f"  OK  {result['skill_name']}: {result.get('action', '')}")
            if result.get("warnings"):
                for w in result["warnings"]:
                    print(f"      WARN: {w}")
        elif result["status"] == "skipped":
            skipped += 1
            if args.verbose:
                print(f" SKIP  {result['skill_name']}: {result.get('reason', '')}")
        else:
            errors += 1
            print(f" FAIL  {result['skill_name']}: {result.get('error', 'unknown')}")

    print(f"\nDone: {converted} converted, {skipped} skipped, {errors} errors (total: {total})")


if __name__ == "__main__":
    main()
